<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>4.4.0.0</Version>
    <Authors>Sergio</Authors>
    <Company>Sergio</Company>
    <Product>WhisperSubs</Product>
    <Description>Automated subtitle generation for Jellyfin using local AI models.</Description>
    <PackageId>WhisperSubs</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Model" Version="10.11.0" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Web\configPage.html" />
    <None Remove="Web\whisperSubs.js" />
    <EmbeddedResource Include="Web\configPage.html" />
    <EmbeddedResource Include="Web\whisperSubs.js" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="WhisperSubs.Tests\**" />
    <EmbeddedResource Remove="WhisperSubs.Tests\**" />
    <None Remove="WhisperSubs.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WhisperSubs.Tests" />
  </ItemGroup>

</Project>
